server:
  port: 8081

spring:
  flyway:
    enabled: true
    create-schema: true
    baseline-on-migrate: true
    default-schema: book_sphere
    locations: classpath:db.migration

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:booksphere}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_schema: book_sphere
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  redis:
    verification:
      ttl-minutes: 2

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_UEL:http://localhost:8080/realms/BookSphere}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8080/realms/BookSphere/protocol/openid-connect/certs}

  keycloak:
    rest:
      realm: BookSphere
      client-id: booksphere-rest-api
      client-secret: ${KEYCLOAK_CLIENT_SECRET:7OJNdX4lOrI70qv3BnzRGDHxWLx2LipV}
      token-uri: ${KEYCLOAK_URL:http://localhost:8080}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:book.sphere.api@gmail.com}
    password: ${MAIL_PASSWORD:wwso vcoa rpsy akew}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

minio:
  url: ${MINIO_URL:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:admin}
  secretKey: ${MINIO_SECRET_KEY:password}
  bucket-name: user-image-bucket
  secure: false

book:
  upload:
    min-size: 1MB
    max-size: 100MB