// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { ChangePasswordData, ChangePasswordResponses, ChangePersonalDataData, ChangePersonalDataResponses, DeleteAccountData, DeleteAccountResponses, GetBooksData, GetBooksResponses, GetMyLibraryData, GetMyLibraryResponses, GetPersonalProfileData, GetPersonalProfileResponses, GetUserLibraryData, GetUserLibraryResponses, GetUserProfileData, GetUserProfileResponses, HandleUserVerificationData, HandleUserVerificationResponses, LoginData, LoginResponses, MarkAsReadingData, MarkAsReadingResponses, ReadBookData, ReadBookResponses, RefreshTokenData, RefreshTokenResponses, RegistrationData, RegistrationResponses, SearchUserData, SearchUserResponses, SendVerificationMailData, SendVerificationMailResponses, UpdateBookStatusData, UpdateBookStatusResponses, UploadBookData, UploadBookResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const changePersonalData = <ThrowOnError extends boolean = false>(options: Options<ChangePersonalDataData, ThrowOnError>) => (options.client ?? client).put<ChangePersonalDataResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/user-change',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const sendVerificationMail = <ThrowOnError extends boolean = false>(options?: Options<SendVerificationMailData, ThrowOnError>) => (options?.client ?? client).post<SendVerificationMailResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/verification/send',
    ...options
});

export const handleUserVerification = <ThrowOnError extends boolean = false>(options: Options<HandleUserVerificationData, ThrowOnError>) => (options.client ?? client).post<HandleUserVerificationResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/verification/handle',
    ...options
});

export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>) => (options.client ?? client).post<ChangePasswordResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const uploadBook = <ThrowOnError extends boolean = false>(options?: Options<UploadBookData, ThrowOnError>) => (options?.client ?? client).post<UploadBookResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/book/upload-book',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

export const registration = <ThrowOnError extends boolean = false>(options: Options<RegistrationData, ThrowOnError>) => (options.client ?? client).post<RegistrationResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/registration',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const refreshToken = <ThrowOnError extends boolean = false>(options: Options<RefreshTokenData, ThrowOnError>) => (options.client ?? client).post<RefreshTokenResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/refresh-token',
    ...options
});

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const updateBookStatus = <ThrowOnError extends boolean = false>(options: Options<UpdateBookStatusData, ThrowOnError>) => (options.client ?? client).patch<UpdateBookStatusResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/book/update-book-status/{bookId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const markAsReading = <ThrowOnError extends boolean = false>(options: Options<MarkAsReadingData, ThrowOnError>) => (options.client ?? client).patch<MarkAsReadingResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/book/mark-as-reading/{bookId}',
    ...options
});

export const getUserProfile = <ThrowOnError extends boolean = false>(options: Options<GetUserProfileData, ThrowOnError>) => (options.client ?? client).get<GetUserProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/{userId}',
    ...options
});

export const searchUser = <ThrowOnError extends boolean = false>(options: Options<SearchUserData, ThrowOnError>) => (options.client ?? client).get<SearchUserResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/search',
    ...options
});

export const getPersonalProfile = <ThrowOnError extends boolean = false>(options?: Options<GetPersonalProfileData, ThrowOnError>) => (options?.client ?? client).get<GetPersonalProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/profile',
    ...options
});

export const getUserLibrary = <ThrowOnError extends boolean = false>(options: Options<GetUserLibraryData, ThrowOnError>) => (options.client ?? client).get<GetUserLibraryResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/book/user-library/{userId}',
    ...options
});

export const getBooks = <ThrowOnError extends boolean = false>(options: Options<GetBooksData, ThrowOnError>) => (options.client ?? client).get<GetBooksResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/book/search-books',
    ...options
});

export const readBook = <ThrowOnError extends boolean = false>(options: Options<ReadBookData, ThrowOnError>) => (options.client ?? client).get<ReadBookResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/book/read-book/{bookId}',
    ...options
});

export const getMyLibrary = <ThrowOnError extends boolean = false>(options?: Options<GetMyLibraryData, ThrowOnError>) => (options?.client ?? client).get<GetMyLibraryResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/book/my-library',
    ...options
});

export const deleteAccount = <ThrowOnError extends boolean = false>(options: Options<DeleteAccountData, ThrowOnError>) => (options.client ?? client).delete<DeleteAccountResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/user/delete-account',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
