// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8081' | (string & {});
};

export type UserEditDto = {
    email?: string;
    firstName?: string;
    lastName?: string;
};

export type ChangePasswordDto = {
    oldPassword: string;
    newPassword: string;
};

export type LoginResponse = {
    access_token?: string;
    expires_in?: number;
    refresh_token?: string;
    refresh_expires_in?: number;
};

export type BookUploadDto = {
    title: string;
    author: string;
    categoryId?: number;
    file?: Blob | File;
};

export type UserCreateDto = {
    username: string;
    email: string;
    password: string;
    firstName: string;
    lastName: string;
};

export type UserReadDto = {
    userId?: string;
    username?: string;
    fullName?: string;
};

export type LoginDto = {
    email?: string;
    password?: string;
};

export type BookProgressUpdateDto = {
    currentPage: number;
};

export type PublicProfileDto = {
    username?: string;
    firstName?: string;
    lastName?: string;
};

export type CustomPage = {
    totalElements?: number;
    totalPage?: number;
    page?: number;
    size?: number;
};

export type PageDtoUserReadDto = {
    content?: Array<UserReadDto>;
    customPage?: CustomPage;
};

export type PrivateProfileDto = {
    username?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type ForeignLibraryDto = {
    bookId?: string;
    title?: string;
    author?: string;
    imageUrl?: string;
    categoryName?: string;
    readStatus?: 'WANT_TO_READ' | 'READING' | 'FINISHED';
};

export type PageDtoForeignLibraryDto = {
    content?: Array<ForeignLibraryDto>;
    customPage?: CustomPage;
};

export type BookSearchDto = {
    bookId?: string;
    title?: string;
    author?: string;
    imageUrl?: string;
};

export type PageDtoBookSearchDto = {
    content?: Array<BookSearchDto>;
    customPage?: CustomPage;
};

export type MyLibraryDto = {
    bookId?: string;
    title?: string;
    author?: string;
    imageUrl?: string;
    categoryName?: string;
    readingStatus?: 'WANT_TO_READ' | 'READING' | 'FINISHED';
    bookMarkPage?: number;
    readPercentage?: number;
};

export type PageDtoMyLibraryDto = {
    content?: Array<MyLibraryDto>;
    customPage?: CustomPage;
};

export type UserDeleteDto = {
    password: string;
};

export type ChangePersonalDataData = {
    body: UserEditDto;
    path?: never;
    query?: never;
    url: '/api/user/user-change';
};

export type ChangePersonalDataResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SendVerificationMailData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/verification/send';
};

export type SendVerificationMailResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type HandleUserVerificationData = {
    body?: never;
    path?: never;
    query: {
        code: string;
    };
    url: '/api/user/verification/handle';
};

export type HandleUserVerificationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ChangePasswordData = {
    body: ChangePasswordDto;
    path?: never;
    query?: never;
    url: '/api/user/password';
};

export type ChangePasswordResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type UploadBookData = {
    body?: BookUploadDto;
    path?: never;
    query?: never;
    url: '/api/book/upload-book';
};

export type UploadBookResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RegistrationData = {
    body: UserCreateDto;
    path?: never;
    query?: never;
    url: '/api/auth/registration';
};

export type RegistrationResponses = {
    /**
     * Created
     */
    201: UserReadDto;
};

export type RegistrationResponse = RegistrationResponses[keyof RegistrationResponses];

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query: {
        refresh_token: string;
    };
    url: '/api/auth/refresh-token';
};

export type RefreshTokenResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type LoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type UpdateBookStatusData = {
    body: BookProgressUpdateDto;
    path: {
        bookId: string;
    };
    query?: never;
    url: '/api/book/update-book-status/{bookId}';
};

export type UpdateBookStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MarkAsReadingData = {
    body?: never;
    path: {
        bookId: string;
    };
    query?: never;
    url: '/api/book/mark-as-reading/{bookId}';
};

export type MarkAsReadingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUserProfileData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/user/{userId}';
};

export type GetUserProfileResponses = {
    /**
     * OK
     */
    200: PublicProfileDto;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type SearchUserData = {
    body?: never;
    path?: never;
    query: {
        username: string;
        page?: number;
        size?: number;
    };
    url: '/api/user/search';
};

export type SearchUserResponses = {
    /**
     * OK
     */
    200: PageDtoUserReadDto;
};

export type SearchUserResponse = SearchUserResponses[keyof SearchUserResponses];

export type GetPersonalProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/profile';
};

export type GetPersonalProfileResponses = {
    /**
     * OK
     */
    200: PrivateProfileDto;
};

export type GetPersonalProfileResponse = GetPersonalProfileResponses[keyof GetPersonalProfileResponses];

export type GetUserLibraryData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        page?: number;
        size?: number;
    };
    url: '/api/book/user-library/{userId}';
};

export type GetUserLibraryResponses = {
    /**
     * OK
     */
    200: PageDtoForeignLibraryDto;
};

export type GetUserLibraryResponse = GetUserLibraryResponses[keyof GetUserLibraryResponses];

export type GetBooksData = {
    body?: never;
    path?: never;
    query: {
        query: string;
        categoryId: number;
        sortFilter: string;
        page?: number;
        size?: number;
    };
    url: '/api/book/search-books';
};

export type GetBooksResponses = {
    /**
     * OK
     */
    200: PageDtoBookSearchDto;
};

export type GetBooksResponse = GetBooksResponses[keyof GetBooksResponses];

export type ReadBookData = {
    body?: never;
    path: {
        bookId: string;
    };
    query?: never;
    url: '/api/book/read-book/{bookId}';
};

export type ReadBookResponses = {
    /**
     * OK
     */
    200: string;
};

export type ReadBookResponse = ReadBookResponses[keyof ReadBookResponses];

export type GetMyLibraryData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/api/book/my-library';
};

export type GetMyLibraryResponses = {
    /**
     * OK
     */
    200: PageDtoMyLibraryDto;
};

export type GetMyLibraryResponse = GetMyLibraryResponses[keyof GetMyLibraryResponses];

export type DeleteAccountData = {
    body: UserDeleteDto;
    path?: never;
    query?: never;
    url: '/api/user/delete-account';
};

export type DeleteAccountResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];
